title: Damian.co
email: d@damian.co
description: > 
  Nothing will work unless you do. —Dr. Maya Angelou
baseurl: "/"
url: "https://damian.co"
twitter_username: @damianhakert
github_username:  @damianhakert

# Build settings
markdown: kramdown
theme: minima
gems:
  - jekyll-feed
  - jekyll-mentions
exclude:
  - Gemfile
  - Gemfile.lock
